# Generated by Django 5.2.7 on 2025-10-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0002_order_payment_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
