# Generated by Django 5.2.7 on 2025-10-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0003_payment_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_payout',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
