# Generated by Django 5.2.7 on 2025-10-07 10:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0004_alter_payment_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
